// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: causality/v1/service.proto

package causalityv1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// EventServiceClient is the client API for EventService service.
type EventServiceClient interface {
	IngestEvent(ctx context.Context, req *IngestEventRequest, opts ...EventServiceCallOption) (*IngestEventResponse, error)
	IngestEventBatch(ctx context.Context, req *IngestEventBatchRequest, opts ...EventServiceCallOption) (*IngestEventBatchResponse, error)
}

// eventServiceClient is the implementation of EventServiceClient.
type eventServiceClient struct {
	baseURL        string
	httpClient     *http.Client
	contentType    string
	defaultHeaders map[string]string
}

var _ EventServiceClient = (*eventServiceClient)(nil)

// EventServiceClientOption configures a EventService client.
type EventServiceClientOption func(*eventServiceClient)

// WithEventServiceHTTPClient sets the HTTP client to use for requests.
func WithEventServiceHTTPClient(client *http.Client) EventServiceClientOption {
	return func(c *eventServiceClient) {
		c.httpClient = client
	}
}

// WithEventServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithEventServiceContentType(contentType string) EventServiceClientOption {
	return func(c *eventServiceClient) {
		c.contentType = contentType
	}
}

// WithEventServiceDefaultHeader sets a default header to include in all requests.
func WithEventServiceDefaultHeader(key, value string) EventServiceClientOption {
	return func(c *eventServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// EventServiceCallOption configures a single RPC call.
type EventServiceCallOption func(*eventServiceCallOptions)

// eventServiceCallOptions holds options for a single RPC call.
type eventServiceCallOptions struct {
	headers     map[string]string
	contentType string
}

// WithEventServiceHeader adds a header to a single request.
func WithEventServiceHeader(key, value string) EventServiceCallOption {
	return func(o *eventServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithEventServiceCallContentType sets the content type for a single request.
func WithEventServiceCallContentType(contentType string) EventServiceCallOption {
	return func(o *eventServiceCallOptions) {
		o.contentType = contentType
	}
}

// NewEventServiceClient creates a new EventService client.
func NewEventServiceClient(baseURL string, opts ...EventServiceClientOption) EventServiceClient {
	c := &eventServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// IngestEvent calls the IngestEvent RPC.
func (c *eventServiceClient) IngestEvent(ctx context.Context, req *IngestEventRequest, opts ...EventServiceCallOption) (*IngestEventResponse, error) {
	callOpts := &eventServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/events/ingest"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Unmarshal response
	result := &IngestEventResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// IngestEventBatch calls the IngestEventBatch RPC.
func (c *eventServiceClient) IngestEventBatch(ctx context.Context, req *IngestEventBatchRequest, opts ...EventServiceCallOption) (*IngestEventBatchResponse, error) {
	callOpts := &eventServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/events/batch"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Unmarshal response
	result := &IngestEventBatchResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *eventServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *eventServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *eventServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON unmarshaler (unwrap support)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		return protojson.Unmarshal(body, msg)
	}
}
