// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: causality/v1/service.proto

package causalityv1

import (
	"context"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error)
	IngestEventBatch(context.Context, *IngestEventBatchRequest) (*IngestEventBatchResponse, error)
}

// RegisterEventServiceServer registers the HTTP handlers for service EventService to the given mux.
func RegisterEventServiceServer(server EventServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getEventServiceHeaders()

	methodHeaders := getIngestEventHeaders()
	ingestEventHandler := BindingMiddleware[IngestEventRequest](
		genericHandler(server.IngestEvent, config.errorHandler), serviceHeaders, methodHeaders,
		ingestEventPathParams, ingestEventQueryParams,
		"POST", config.errorHandler,
	)

	config.mux.Handle("POST /v1/events/ingest", ingestEventHandler)

	methodHeaders = getIngestEventBatchHeaders()
	ingestEventBatchHandler := BindingMiddleware[IngestEventBatchRequest](
		genericHandler(server.IngestEventBatch, config.errorHandler), serviceHeaders, methodHeaders,
		ingestEventBatchPathParams, ingestEventBatchQueryParams,
		"POST", config.errorHandler,
	)

	config.mux.Handle("POST /v1/events/batch", ingestEventBatchHandler)

	return nil
}

// getEventServiceHeaders returns the service-level required headers for EventService
func getEventServiceHeaders() []*sebufhttp.Header {
	return nil
}

// getIngestEventHeaders returns the method-level required headers for IngestEvent
func getIngestEventHeaders() []*sebufhttp.Header {
	return nil
}

// getIngestEventBatchHeaders returns the method-level required headers for IngestEventBatch
func getIngestEventBatchHeaders() []*sebufhttp.Header {
	return nil
}

// ingestEventPathParams contains path parameter configuration for IngestEvent
var ingestEventPathParams = []PathParamConfig{}

// ingestEventQueryParams contains query parameter configuration for IngestEvent
var ingestEventQueryParams = []QueryParamConfig{}

// ingestEventBatchPathParams contains path parameter configuration for IngestEventBatch
var ingestEventBatchPathParams = []PathParamConfig{}

// ingestEventBatchQueryParams contains query parameter configuration for IngestEventBatch
var ingestEventBatchQueryParams = []QueryParamConfig{}
