// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: causality/v1/service.proto

package causalityv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IngestEventRequest is the request for single event ingestion.
type IngestEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event to ingest
	Event         *EventEnvelope `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventRequest) Reset() {
	*x = IngestEventRequest{}
	mi := &file_causality_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventRequest) ProtoMessage() {}

func (x *IngestEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_causality_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventRequest.ProtoReflect.Descriptor instead.
func (*IngestEventRequest) Descriptor() ([]byte, []int) {
	return file_causality_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *IngestEventRequest) GetEvent() *EventEnvelope {
	if x != nil {
		return x.Event
	}
	return nil
}

// IngestEventResponse is the response for single event ingestion.
type IngestEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The assigned event ID (UUID v7)
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Status of the ingestion
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventResponse) Reset() {
	*x = IngestEventResponse{}
	mi := &file_causality_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventResponse) ProtoMessage() {}

func (x *IngestEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_causality_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventResponse.ProtoReflect.Descriptor instead.
func (*IngestEventResponse) Descriptor() ([]byte, []int) {
	return file_causality_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *IngestEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// IngestEventBatchRequest is the request for batch event ingestion.
type IngestEventBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events to ingest (max 1000 per batch)
	Events        []*EventEnvelope `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventBatchRequest) Reset() {
	*x = IngestEventBatchRequest{}
	mi := &file_causality_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventBatchRequest) ProtoMessage() {}

func (x *IngestEventBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_causality_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestEventBatchRequest) Descriptor() ([]byte, []int) {
	return file_causality_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *IngestEventBatchRequest) GetEvents() []*EventEnvelope {
	if x != nil {
		return x.Events
	}
	return nil
}

// IngestEventBatchResponse is the response for batch event ingestion.
type IngestEventBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of events accepted
	AcceptedCount int32 `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	// Number of events rejected due to validation errors
	RejectedCount int32 `protobuf:"varint,2,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	// Individual event results
	Results       []*EventResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventBatchResponse) Reset() {
	*x = IngestEventBatchResponse{}
	mi := &file_causality_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventBatchResponse) ProtoMessage() {}

func (x *IngestEventBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_causality_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestEventBatchResponse) Descriptor() ([]byte, []int) {
	return file_causality_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *IngestEventBatchResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *IngestEventBatchResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *IngestEventBatchResponse) GetResults() []*EventResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// EventResult contains the result of a single event in a batch.
type EventResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of the event in the request batch
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// The assigned event ID (UUID v7) if accepted
	EventId string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Status: "accepted" or "rejected"
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Error message if rejected
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResult) Reset() {
	*x = EventResult{}
	mi := &file_causality_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResult) ProtoMessage() {}

func (x *EventResult) ProtoReflect() protoreflect.Message {
	mi := &file_causality_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResult.ProtoReflect.Descriptor instead.
func (*EventResult) Descriptor() ([]byte, []int) {
	return file_causality_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *EventResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EventResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_causality_v1_service_proto protoreflect.FileDescriptor

const file_causality_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1acausality/v1/service.proto\x12\fcausality.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a\x19causality/v1/events.proto\"O\n" +
	"\x12IngestEventRequest\x129\n" +
	"\x05event\x18\x01 \x01(\v2\x1b.causality.v1.EventEnvelopeB\x06\xbaH\x03\xc8\x01\x01R\x05event\"H\n" +
	"\x13IngestEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"[\n" +
	"\x17IngestEventBatchRequest\x12@\n" +
	"\x06events\x18\x01 \x03(\v2\x1b.causality.v1.EventEnvelopeB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\x06events\"\x9d\x01\n" +
	"\x18IngestEventBatchResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x02 \x01(\x05R\rrejectedCount\x123\n" +
	"\aresults\x18\x03 \x03(\v2\x19.causality.v1.EventResultR\aresults\"l\n" +
	"\vEventResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xf4\x01\n" +
	"\fEventService\x12a\n" +
	"\vIngestEvent\x12 .causality.v1.IngestEventRequest\x1a!.causality.v1.IngestEventResponse\"\r\x9a\xb5\x18\t\n" +
	"\a/ingest\x12o\n" +
	"\x10IngestEventBatch\x12%.causality.v1.IngestEventBatchRequest\x1a&.causality.v1.IngestEventBatchResponse\"\f\x9a\xb5\x18\b\n" +
	"\x06/batch\x1a\x10\xa2\xb5\x18\f\n" +
	"\n" +
	"/v1/eventsB\xb9\x01\n" +
	"\x10com.causality.v1B\fServiceProtoP\x01ZFgithub.com/SebastienMelki/causality/pkg/proto/causality/v1;causalityv1\xa2\x02\x03CXX\xaa\x02\fCausality.V1\xca\x02\fCausality\\V1\xe2\x02\x18Causality\\V1\\GPBMetadata\xea\x02\rCausality::V1b\x06proto3"

var (
	file_causality_v1_service_proto_rawDescOnce sync.Once
	file_causality_v1_service_proto_rawDescData []byte
)

func file_causality_v1_service_proto_rawDescGZIP() []byte {
	file_causality_v1_service_proto_rawDescOnce.Do(func() {
		file_causality_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_causality_v1_service_proto_rawDesc), len(file_causality_v1_service_proto_rawDesc)))
	})
	return file_causality_v1_service_proto_rawDescData
}

var file_causality_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_causality_v1_service_proto_goTypes = []any{
	(*IngestEventRequest)(nil),       // 0: causality.v1.IngestEventRequest
	(*IngestEventResponse)(nil),      // 1: causality.v1.IngestEventResponse
	(*IngestEventBatchRequest)(nil),  // 2: causality.v1.IngestEventBatchRequest
	(*IngestEventBatchResponse)(nil), // 3: causality.v1.IngestEventBatchResponse
	(*EventResult)(nil),              // 4: causality.v1.EventResult
	(*EventEnvelope)(nil),            // 5: causality.v1.EventEnvelope
}
var file_causality_v1_service_proto_depIdxs = []int32{
	5, // 0: causality.v1.IngestEventRequest.event:type_name -> causality.v1.EventEnvelope
	5, // 1: causality.v1.IngestEventBatchRequest.events:type_name -> causality.v1.EventEnvelope
	4, // 2: causality.v1.IngestEventBatchResponse.results:type_name -> causality.v1.EventResult
	0, // 3: causality.v1.EventService.IngestEvent:input_type -> causality.v1.IngestEventRequest
	2, // 4: causality.v1.EventService.IngestEventBatch:input_type -> causality.v1.IngestEventBatchRequest
	1, // 5: causality.v1.EventService.IngestEvent:output_type -> causality.v1.IngestEventResponse
	3, // 6: causality.v1.EventService.IngestEventBatch:output_type -> causality.v1.IngestEventBatchResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_causality_v1_service_proto_init() }
func file_causality_v1_service_proto_init() {
	if File_causality_v1_service_proto != nil {
		return
	}
	file_causality_v1_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_causality_v1_service_proto_rawDesc), len(file_causality_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_causality_v1_service_proto_goTypes,
		DependencyIndexes: file_causality_v1_service_proto_depIdxs,
		MessageInfos:      file_causality_v1_service_proto_msgTypes,
	}.Build()
	File_causality_v1_service_proto = out.File
	file_causality_v1_service_proto_goTypes = nil
	file_causality_v1_service_proto_depIdxs = nil
}
